title: EQE359 - Termodinamica I
description: Material complementar para o curso de Termodinâmica I - Fred Tavares, Iuri Segtovich.

theme: jekyll-theme-tactile

show_downloads: true

github:
  public: true
